name: 🚀 Release Parsely AI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        cd src
        python -m build
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Parsely AI ${{ github.ref }}
        body: |
          🌿 Fresh release of Parsely AI!
          
          ## What's New
          - Enhanced document processing capabilities
          - Improved Gemini AI integration
          - Better error handling and logging
          - Performance optimizations
          
          ## Installation
          ```bash
          git clone https://github.com/yourusername/parsely-ai.git
          cd parsely-ai
          pip install -r requirements.txt
          ```
          
          ## Docker
          ```bash
          docker pull parsely-ai:${{ github.ref_name }}
          ```
          
          See the [README](README.md) for full installation and usage instructions.
        draft: false
        prerelease: false